services:
  model:
    build:       
      dockerfile: Dockerfile.fastapi
      context: ./
    volumes: 
      - ./test_model:/app
    ports:
      - "8000:8000"
  streamlit:
    build: 
      dockerfile: Dockerfile.streamlit
      context: ./
    volumes: 
      - ./app:/app
    ports:
      - "8501:8501"
